modified scripts

diff --git a/.local/bin/folderfind b/.local/bin/folderfind
--- a/.local/bin/folderfind
+++ b/.local/bin/folderfind
@@ -1,18 +1,21 @@
 #!/bin/bash
 
-# Run fzfmenu.sh to get the selected directory
-selected_dir=$(fd --type directory --hidden . ~ | fuzzel --dmenu)
-[ -z "$selected_dir" ] && exit 1
+# check dependencies
+if command -v fuzzel &>/dev/null; then
+  echo "error: fuzzel is not available"
+  exit 1
+fi
 
-# Get the action to perform
+# variables
+selected_dir=$(fd --type directory --hidden . ~ | fuzzel --dmenu)
+[ -z "$selected_dir" ] && exit 2
 index=$(
   printf "1 Terminal Tmux\0icon\x1ffoot\n2 Dolphin\0icon\x1forg.kde.dolphin\n3 Yazi\0icon\x1fyazi\n4 Nvim\0icon\x1fnvim" |
     fuzzel --dmenu |
     awk '{ print $1 }'
 )
-[ -z "$index" ] && exit 2
+[ -z "$index" ] && exit 3
 
-# Perform the action
 case $index in
 1) foot --working-directory "$selected_dir" -e sh -c "tmux -u new-session" ;;
 2) dolphin "$selected_dir" ;;
diff --git a/.local/bin/media b/.local/bin/media
--- a/.local/bin/media
+++ b/.local/bin/media
@@ -1,83 +1,70 @@
 #!/bin/sh
 
-# This is a wrapper script for playerctl that only controls a specific media player stored in $HOME/.cache/.player.txt
-# Functions
+# this is a wrapper script for playerctl that only
+# controls a specific media player stored in $default_player.
+
+# variables 
+media_file="$HOME/.local/state/default_player.txt"
+[ -f "$media_file" ] || : >"$media_file"
+top_player=$(playerctl -l 2>/dev/null | head -n1)
+chosen_player=$(cat "$media_file")
+[ -z "$chosen_player" ] && chosen_player="$top_player"
+
+# functions
 help() {
-  printf "Usage: %s [Option]\n\nOptions:\nhelp: print this manual.\nplay-pause: toggle the media playing.\nvolume [0-1]<+/-/nothing>\nnext: play next media.\nprevious: play previous media.\nloop: toggle loop state.\n" "$command"
-}
+  cat <<EOF
+Usage: $0 <arg>
 
+Arguments:
+  play-pause:    toggle the media playing.
+  volume:        <percentage>[+|-]
+  next:          play next media.
+  previous:      play previous media.
+  loop:          toggle loop state.
+  -h | --help | help
+                print this message
+  EOF
+}
 toggleplay() {
-  playerctl $args play-pause
+  playerctl --player "$chosen_player" play-pause
 }
-
 volume() {
-  number=$(echo -n "$1" | grep -Eo "[0-9]+")
-  operator=$(echo -n "$1" | grep -Eo "(\+)|(-)")
-
-  ! $isPlayerMpd && {
-    number=$(echo "scale=2; $number / 100" | bc)
-    playerctl $args volume "$number$operator"
-  } ||
-    mpc volume "$operator$number"
+  number=$(printf '%s' "$1" | grep -Eo "[0-9]+")
+  number=$(echo "scale=2; $number / 100" | bc)
+  operator=$(printf '%s' "$1" | grep -Eo "(\+)|(-)")
+  [ -z "$number" ] && exit 1
+  playerctl --player "$chosen_player" volume "$number$operator"
 }
-
 next() {
-  playerctl $args next
+  playerctl --player "$chosen_player" next
 }
-
 prev() {
-  playerctl $args previous
+  playerctl --player "$chosen_player" previous
 }
-
 toggleloop() {
-  playerctl $args loop | grep -qi "none" &&
-    playerctl $args loop track ||
-    playerctl $args loop none
+  [ -z "$chosen_player" ] && echo "no media playing" && exit 2
+  if playerctl --player "$chosen_player" loop | grep -qi none; then
+      playerctl --player "$chosen_player" loop track
+  else
+      playerctl --player "$chosen_player" loop none
+  fi
 }
-
 choose() {
-  chosen=$(playerctl -l | fuzzel --dmenu "Choose Player")
-  printf "$chosen" >$HOME/.cache/.player.txt 2>/dev/null
+  chosen="$(playerctl -l | fuzzel --dmenu "Choose a media player")"
+  echo "$chosen"  >"$media_file" 2>/dev/null
 }
 
-# Variable Initialization
-topPlayer=$(playerctl -l | head -n 1)
-chosen=$(cat $HOME/.cache/.player.txt)
-[ -n "$chosen" ] && args="--player $chosen"
-command="$0"
-
-# Start
-echo "chosen: $chosen"
-if [ -n "$chosen" ]; then
-  [ "$chosen" = "mpd" ] && isPlayerMpd=true || isPlayerMpd=false
-else
-  [ "$topPlayer" = "mpd" ] && isPlayerMpd=true || isPlayerMpd=false
-fi
-
+# start
 case "$1" in
-"help" | "--help")
-  help
-  ;;
-"play-pause")
-  toggleplay
-  ;;
-"volume")
-  volume "$2"
-  ;;
-"next")
-  next
-  ;;
-"previous")
-  prev
-  ;;
-"loop")
-  toggleloop
-  ;;
-"choose")
-  choose
-  ;;
+"help" | "--help") help ;;
+"play-pause") toggleplay ;;
+"volume") volume "$2" ;;
+"next") next ;;
+"previous") prev ;;
+"loop") toggleloop ;;
+"choose") choose ;;
 *)
-  printf "invalid option.\n\n"
-  help
+  echo "invalid argument. use -h or --help for help"
+  exit 3
   ;;
 esac
