Fixed and changed files

diff --git a/.local/bin/passget b/.local/bin/passget
--- a/.local/bin/passget
+++ b/.local/bin/passget
@@ -6,19 +6,20 @@ password_dir="$HOME/files/privateFiles/.password-store"
 ## Setting environment variable for Termux:Widget
 export PASSWORD_STORE_DIR=$password_dir
 
+# Check for dependencies
+[ ! -f "$HOME/.local/bin/clipboard" ] && 
+  echo "Dependency $HOME/.local/bin/clipboard not found." &&
+  exit 1
+
 ## Get password name
 password_name=$(ls $password_dir | sed '/\.gpg-id$/d; s/\.gpg$//' | fzf --pointer '=>' --layout reverse --info hidden --header 'Select a Password')
 
 # Check for errors
 ## Check if password exists
-[ ! -f "$password_dir/$password_name.gpg" ] && echo "$password_name does not exist." && exit 1
+[ ! -f "$password_dir/$password_name.gpg" ] && echo "$password_name does not exist." && exit 2
 
 # Copy password to clipboard on various environments
-## Termux specific command
-[ -n "$TERMUX_VERSION" ] && pass "$password_name" | termux-clipboard-set
-
-## WSL specific command
-[ -n "$WSL_DISTRO_NAME" ] && pass "$password_name" | clip.exe
+pass "$password_name" | ~/.local/bin/clipboard
 
 # Add a new line at the end of script
 echo ""
